# Generated by Django 3.0.5 on 2020-05-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200509_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='title',
            field=models.CharField(default='django', max_length=50),
            preserve_default=False,
        ),
    ]
