f = open('data.txt','w')
print(f.write('Hello\n'))
print(f.write('World'))
dir(f)
f.close()
rf = open('data.txt')
text = rf.read()
print(text)
obj1 = text.split()
print(type(obj1))
print(obj1)
rf.close()
print('-------')
data = open('data.txt', 'rb').read()
print(data)
print(data[4:9])
